ci:
  skip: [mypy, pytest]
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.12.0
    hooks:
    - id: pyupgrade
      args: [--py38-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
      - id: pylint
        additional_dependencies: [torch, pytest]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true

      - id: pytest
        name: pytest
        entry: pytest --cov=torchinfo --cov-report=html --durations=0
        language: python
        types: [python]
        always_run: true
        pass_filenames: false
        verbose: true
